### ISSUE TITLE
How to reproduce the results on the leaderboard

### ISSUE THREAD

**Issue by xyz8** [oaqa/FlexNeuART#7]
I want to know how to reproduce the results on the MS MARCO leaderboard:
Document Retrieval:
BERT-m1 base + classic IR + doc2query (ensemble) -Eval 0.398 
BERT-m1 base (v3) / traditional IR + doc2query - Eval 0.396
Passage Retrieval:
expando-mono-duo-T5 - Eval 0.408
Thanks!

**Comment by searchivarius** [comment]
Hi @xyz8 thank you for the interest, I am not the one who submitted expando-mono-duo-T5. I would like at some point to provide code for full or at least partial reproduction (maybe not the latest model). However, given a competitive nature of this leaderboard this is not going to happen soon.

**Comment by xyz8** [comment]
I got it. Thanks for your quick reply.  I was just curious about the SOTA model on the leaderboard but found nothing in "[paper][code]". Look forward to your model to achieve better results.

**Comment by searchivarius** [comment]
@xyz8 the paper was under review and it needs clearance to be published.

**Comment by searchivarius** [comment]
Hi @xyz8 there's now a paper, but there's some extra effort put into training a leaderboard model such longer training, proper ensembling, using a stronger first stage pipeline (now it's enriched traditional). I hope to release the first stage pipeline though (ast least up to 200 candidates per query in dev & validation). Paper:

https://arxiv.org/abs/2102.06815

The best classic IR runs could be fully reproduced:
https://github.com/oaqa/FlexNeuART/blob/master/scripts/data_convert/msmarco/README.md

**Comment by xyz8** [comment]
Thank you for your sharing.

**Comment by searchivarius** [comment]
PS: model code isn't released yet: it will take some work to do (clearance, etc).
